//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LockedPower.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LockedPower.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] balance10_29_01_2020 {
            get {
                object obj = ResourceManager.GetObject("balance10_29_01_2020", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Омской области
        ///Новосибирской области
        ///Республики Алтай и Алтайского края
        ///Кемеровской области
        ///Томской области
        ///Республики Хакасия
        ///Красноярского края и Республики Тыва (по территории Красноярского края)
        ///Красноярского края и Республики Тыва (по территории Республики Тыва)
        ///Иркутской области
        ///Республики Бурятии
        ///Забайкальского края
        ///ОЭС Сибири.
        /// </summary>
        internal static string EnergySystems {
            get {
                return ResourceManager.GetString("EnergySystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устан. мощн.
        ///Огран.
        ///Расп. мощн.
        ///Всего
        ///ВПр
        ///Рек
        ///КС
        ///ЗРР
        ///Раб. мощн.
        ///Ген-ция
        ///Вращ. резерв ТЭС
        ///Хол. резерв ТЭС
        ///Перегруз
        ///Час совм. максимума.
        /// </summary>
        internal static string NameOfParameters {
            get {
                return ResourceManager.GetString("NameOfParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ppbr_a__22012020_1 {
            get {
                object obj = ResourceManager.GetObject("ppbr_a__22012020_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бурятия - Иркутск
        ///Камала - Красноярская на запад
        ///Назаровское на запад
        ///Кузбасс-Запад.
        /// </summary>
        internal static string SectionsName {
            get {
                return ResourceManager.GetString("SectionsName", resourceCulture);
            }
        }
    }
}
